## Tutorial App
tutorialApp:
  namespace: tutorial
  appName: kubernetes-bootcamp
  averageUtilization: 10 #10% pour voir les pods scale
  ## Deployment configuration for the Kubernetes Bootcamp application
  deployment:
    replicaCount: 2
    image: registry.k8s.io/minikube/kubernetes-bootcamp:v1
    ressources:
      limits:
        cpu: "1"
        # memory: 512Mi
      requests:
        cpu: 100m # m = milli-coeurs. 100m = 10% d'un coeur CPU.
        # memory: 256Mi
  ## Service configuration for the Kubernetes Bootcamp application
  service:
    name: bootcamp-service
    port: 8080
    targetPort: 8080
    protocol: TCP
    selector:
      app: kubernetes-bootcamp
    type: ClusterIP



###### Traefik Ingress configuration for the Kubernetes Bootcamp application

#### Traefik configuration
traefik:
  namespace: traefik
  name: traefik
  image: traefik:v3.0
  args:
    - --providers.kubernetesingress=true
    - --providers.kubernetesingress.namespaces=
    - --providers.kubernetesingress.ingressclass=traefik # 👈 1. Force Traefik à intercepter la classe 'traefik'
    - --entrypoints.web.address=:80                    
    - --log.level=DEBUG
  container:
    port:
      name: web
      number: 80
  loadbalancer:
    port: 80
    targetPort: 80
  service:
    name: web

# Traffic ingress configuration
ingress:
  metadata:
    name: bootcamp-ingress  
    namespace: tutorial 
  ingressClassName: traefik 
  path: /
  pathType: Prefix
  serviceName: bootcamp-service  
  portNumber: 8080