
#### Traefik configuration
traefik:
  namespace: traefik
  name: traefik
  image: traefik:v3.0
  args:
    - --providers.kubernetesingress=true
    - --providers.kubernetesingress.namespaces=
    - --providers.kubernetesingress.ingressclass=traefik # 👈 1. Force Traefik à intercepter la classe 'traefik'
    - --entrypoints.web.address=:80                    # 👈 2. Écoute sur le port 8000 (évite les blocages de sécurité)
    - --log.level=DEBUG
  container:
    port:
      name: web
      number: 80
  loadbalancer:
    port: 80
    targetPort: 80
  service:
    name: web

# Traffic ingress configuration
ingress:
  metadata:
    name: bootcamp-ingress  
    namespace: tutorial 
  ingressClassName: traefik 
  path: /
  pathType: Prefix
  serviceName: bootcamp-service  
  portNumber: 8080