apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tutorialApp.service.name }}
spec:
  ports:
  - port: {{ .Values.tutorialApp.service.port }}
    targetPort: {{ .Values.tutorialApp.service.targetPort }}
    protocol: {{ .Values.tutorialApp.service.protocol }}
  selector:
    app: {{ .Values.tutorialApp.service.selector.app }}
  type: {{ .Values.tutorialApp.service.type }}
